## Configuracion de Spring
spring:
  application:
    #    name: ms-store-products-fs.up.railway.app
    name: ms-notificaciones
  datasource:
    url: jdbc:postgresql://149.56.110.32:8585/ms-notificaciones
    username: avalon
    password: avalon_psw

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8087

## Configuracion del cliente de Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
    #  defaultZone: ${EUREKA_URL:http://149.56.110.32:8761/eureka}
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-notificaciones
#    non-secure-port-enabled: false
#    secure-port-enabled: true
#    non-secure-port: 80
#    secure-port: 443

jwt:
  secret: HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512
#  expiration: 300000 # Tiempo 5 minutos
  expiration: 31536000000  # Representaría 1,000 años en milisegundos